Job description file for bams preprocessing for a wes library
Ellie Fewings, 26Oct17

TEMPLATE v1

=========== Data location and analysis settings =============

Data server: admin@mgqnap.medschl.cam.ac.uk
Project location: /share/eleanor/gastric_Aug16

project: gastric
library: IGP_L1

======================= HPC settings ========================

working_folder: /scratch/medgen/users/eleanor/Pipeline_working_directory/gastric_Aug16

Account to use for copying source files into HPC: TISCHKOWITZ-SL2
Max time requested for copying source files (hrs.min.sec): 02.00.00

Account to use for bams preprocessing: TISCHKOWITZ-SL2
Max time requested for bams preprocessing (hrs.min.sec): 07.00.00

Account to use for moving results out of HPC: TISCHKOWITZ-SL2
Max time requested for moving results out of HPC (hrs.min.sec): 02.00.00

==================== Pipeline summary =======================

#Pipeline preprocesses dedupped bams and makes g.vcf files for a wes library
#
#Following the Best Practices GATK recommendations the pipeline includes
#- local indel realignment and
#- base quality score recalibration for bams pre-processing
#- haplotype variant caller for generating gvcf files

===================== Standard settings =====================

scripts_folder: /scratch/medgen/scripts/wes_somatic_pipeline_10.17/p03_wes_library_preprocess
start_script: a00_start_pipeline.sh

Tools
-----

tools_folder: /scratch/medgen/tools

java: java/jre1.8.0_40/bin/java

picard: picard/picard-2.6.0/picard.jar
gatk: gatk/gatk-3.6-0/GenomeAnalysisTK.jar

r_folder: r/R-3.2.0/bin

Resources
---------

resources_folder: /scratch/medgen/resources

decompressed_bundle_folder: gatk_bundle/b37/decompressed

ref_genome: human_g1k_v37.fasta

dbsnp: dbsnp_138.b37.vcf
dbsnp129: dbsnp_138.b37.excluding_sites_after_129.vcf

hapmap: hapmap_3.3.b37.vcf
omni: 1000G_omni2.5.b37.vcf
phase1_1k_hc: 1000G_phase1.snps.high_confidence.b37.vcf

indels_1k: 1000G_phase1.indels.b37.vcf
indels_mills: Mills_and_1000G_gold_standard.indels.b37.vcf

targets_folder: illumina_nextera
targets_intervals: nexterarapidcapture_exome_targetedregions_v1.2.b37.intervals

Working sub-folders
-------------------

merged_folder: merged
dedup_bam_folder: f01_bams

processed_folder: processed
logs_folder: f00_logs
proc_bam_folder: f01_bams
idr_folder: f02_idr
bqr_folder: f03_bqr

