Job description file for data export
Ellie Fewings, 26Oct17

TEMPLATE v1

=========== Data location and analysis settings =============

Data server: admin@mgqnap2.medschl.cam.ac.uk
Project location: /share/eleanor/gastric_Aug16

project: gastric
vep annotated dataset: IGP_L1_vqsr_shf_sma_ann

======================= HPC settings ========================

working_folder: /scratch/medgen/users/eleanor/Pipeline_working_directory/gastric_Aug16

Account to use on HPC: TISCHKOWITZ-SL2
Max time to request (hrs.min.sec): 01.00.00

==================== Pipeline summary ======================

# Export selected tables from vep-vcf to txt files
#
# Exported tables:
#
# VCF_VEP annotations
# 1k and Exac annotations
# GT: Alphabetically coded genotype
# GT add, dom, rec: Numerically coded genotypes for additive, dominant and recessive models (biallelic only) 
# GQ: Genotype Quality
# LOD: Likelihoods for normal and tumour genotypes

===================== Standard settings =====================

scripts_folder: /scratch/medgen/scripts/wes_somatic_pipeline_10.17/p07_wes_export_txt
start_script: a00_start_pipeline.sh

Tools
-----

tools_folder: /scratch/medgen/tools
java: java/jre1.8.0_40/bin/java
gatk: gatk/gatk-3.6-0/GenomeAnalysisTK.jar

r_bin_folder: r/R-3.3.2/bin/
r_lib_folder: r/R-3.3.2/lib64/R/library

Note about requirements for R 
-----------------------------
R is used here to genereate html and pdf reports with rmarkdown.
Generating reports with Rmarkdown is pernickety about environment. 
It requires recent versions of several system libraries
and a number of internal R libraries to be pre-installed.
The external libraries are loaded as modules in *.sb.sh script:
module load gcc/5.2.0
module load boost/1.50.0
module load texlive/2015
module load pandoc/1.15.2.1
List of internal r-libraries is in the r-installation notes.
rmarkdown library has to be installed in the r_lib_folder
shown above.

Resources
---------

resources_folder: /scratch/medgen/resources

decompressed_bundle_folder: gatk_bundle/b37/decompressed
ref_genome: human_g1k_v37.fasta

targets_folder: illumina_nextera
targets_intervals: nexterarapidcapture_exome_targetedregions_v1.2.b37.intervals

Additional settings
-------------------

VEP fields: SYMBOL|Allele|Existing_variation|Consequence|IMPACT|CLIN_SIG|SIFT|PolyPhen|cDNA_position|CDS_position|Codons|Protein_position|Amino_acids|DISTANCE|STRAND|SYMBOL_SOURCE
