#!/bin/bash

# a02_report_config.sh
# Reporting settings for filtering step
# Ellie Fewings, 18Oct17

pipeline_info=$(grep "^#" "${job_file}")
pipeline_info=${pipeline_info//"#"/}

echo "------------------- Pipeline summary -----------------"
echo ""
echo "${pipeline_info}"
echo ""
echo "--------- Data location and analysis settings --------"
echo ""
echo "data_server: ${data_server}"
echo "project_location: ${project_location}"
echo ""
echo "project: ${project}"
echo "dataset_name: ${dataset_name}"
echo "filter_name: ${filter_name}"
echo ""
echo "------------------- HPC settings ---------------------"
echo ""
echo "working_folder: ${working_folder}"
echo ""
echo "account_to_use: ${account_to_use}"
echo "time_to_request: ${time_to_request}"
echo ""
echo "----------------- Standard settings ------------------"
echo ""
echo "scripts_folder: ${scripts_folder}"
echo ""
echo "Tools"
echo "-----"
echo ""
echo "tools_folder: ${tools_folder}"
echo ""
echo "java: ${java}"
echo "gatk: ${gatk}"
echo ""
echo "bcftools: ${bcftools}"
echo "plot_vcfstats: ${plot_vcfstats}"
echo ""
echo "python_bin: ${python_bin}"
echo ""
echo "r_folder: ${r_folder}" 
echo "" 
echo "r_bin_folder: ${r_bin_folder}"
echo "r_lib_folder: ${r_lib_folder}"
echo "" 
echo "See note about using different R versions in the job description template"
echo ""
echo "Resources" 
echo "---------"
echo ""
echo "resources_folder: ${resources_folder}"
echo ""
echo "decompressed_bundle_folder: ${decompressed_bundle_folder}"
echo "ref_genome: ${ref_genome}"
echo ""
echo "targets_folder: ${targets_folder}"
echo "targets_intervals: ${targets_intervals}"
#echo "nextera_targets_bed: ${nextera_targets_bed}"
##targets_bed is not used by current pipeline; However it could be used later to target vcf-stats
echo ""
echo "Working sub-folders on HPC"
echo "--------------------------"
echo ""
echo "project_folder: ${project_folder}"
echo ""
echo "filtered_vcf_folder: ${filtered_vcf_folder}"
echo "logs_folder: ${logs_folder}"
echo "histograms_folder: ${histograms_folder}"
echo "vcfstats_folder: ${vcfstats_folder}"
echo "" 