#!/bin/bash

# a02_report_settings.sh
# Report settings for wes library merge pipeline
# Ellie Fewings, 06Oct17

pipeline_info=$(grep "^#" "${job_file}")
pipeline_info=${pipeline_info//"#"/}

echo "------------------- Pipeline summary -----------------"
echo ""
echo "${pipeline_info}"
echo ""
echo "--------- Data location and analysis settings --------"
echo ""
echo "data_server: ${data_server}"
echo "project_location: ${project_location}"
echo ""
echo "project: ${project}"
echo "library: ${library}"
echo "lanes: ${lanes}"
echo ""
echo "tests_set: ${tests_set}"
echo "run_qualimap: ${run_qualimap}"
echo "run_samstat: ${run_samstat}"
echo ""
echo "------------------- HPC settings ---------------------"
echo ""
echo "working_folder: ${working_folder}"
echo "project_folder: ${project_folder}"
echo "library_folder: ${library_folder}"
echo ""
echo "account_copy_in: ${account_copy_in}"
echo "time_copy_in: ${time_copy_in}"
echo ""
echo "account_merge_qc: ${account_merge_qc}"
echo "time_merge_qc: ${time_merge_qc}"
echo ""
echo "account_move_out: ${account_move_out}"
echo "time_move_out: ${time_move_out}"
echo ""
echo "----------------- Standard settings ------------------"
echo ""
echo "scripts_folder: ${scripts_folder}"
echo ""
echo "Tools"
echo "-----"
echo ""
echo "tools_folder: ${tools_folder}"
echo ""
echo "java: ${java}"
echo ""   
echo "samtools: ${samtools}"
echo "samtools_folder: ${samtools_folder}"
echo ""
echo "picard: ${picard}"
echo ""
echo "r_folder: ${r_folder}"
echo ""
echo "qualimap: ${qualimap}"
echo ""
echo "gnuplot: ${gnuplot}"
echo "LiberationSansRegularTTF: ${LiberationSansRegularTTF}"
echo ""
echo "samstat: ${samstat}"
echo ""
echo "Resources" 
echo "---------"
echo ""
echo "resources_folder: ${resources_folder}"
echo ""
echo "ref_genome: ${ref_genome}"
echo ""
echo "bait_set_name: ${bait_set_name}"
echo "probes_intervals: ${probes_intervals}"
echo "targets_intervals: ${targets_intervals}"
echo "targets_bed_3: ${targets_bed_3}"
echo "targets_bed_6: ${targets_bed_6}"
echo ""
echo "Working folders"
echo "---------------"
echo ""
echo "merged_folder: ${merged_folder}"
echo "logs_folder: ${logs_folder}"
echo "bam_folder: ${bam_folder}"
echo "flagstat_folder: ${flagstat_folder}"
echo "picard_mkdup_folder: ${picard_mkdup_folder}"
echo "picard_inserts_folder: ${picard_inserts_folder}"
echo "picard_alignment_folder: ${picard_alignment_folder}"
echo "picard_hybridisation_folder: ${picard_hybridisation_folder}"
echo "picard_summary_folder: ${picard_summary_folder}"
echo "qualimap_results_folder: ${qualimap_results_folder}"
echo "samstat_results_folder: ${samstat_results_folder}"
echo "gatk_diagnose_targets_folder: ${gatk_diagnose_targets_folder}"
echo "gatk_depth_of_coverage_folder: ${gatk_depth_of_coverage_folder}"
echo "" 
