#!/bin/bash

# a02_report_config.sh
# Reporting settings for for splitting and annotating variants
# Ellie Fewings; 25Oct17

pipeline_info=$(grep "^#" "${job_file}")
pipeline_info=${pipeline_info//"#"/}

echo "------------------- Pipeline summary -----------------"
echo ""
echo "${pipeline_info}"
echo ""
echo "--------- Data location and analysis settings --------"
echo ""
echo "data_server: ${data_server}"
echo "project_location: ${project_location}"
echo ""
echo "project: ${project}"
echo "dataset: ${dataset}"
echo ""
echo "------------------- HPC settings ---------------------"
echo ""
echo "working_folder: ${working_folder}"
echo ""
echo "account_to_use: ${account_to_use}"
echo "time_to_request: ${time_to_request}"
echo ""
echo "----------------- Standard settings ------------------"
echo ""
echo "scripts_folder: ${scripts_folder}"
echo ""
echo "Tools"
echo "-----"
echo ""
echo "tools_folder: ${tools_folder}"
echo "java: ${java}"
echo "gatk: ${gatk}"
echo ""
echo "ensembl_version: ${ensembl_version}"
echo "ensembl_api_folder: ${ensembl_api_folder}"
echo "vep_script: ${vep_script}"
echo "vep_cache: ${vep_cache}"
echo ""
echo "Resources" 
echo "---------"
echo ""
echo "resources_folder: ${resources_folder}"
echo ""
echo "decompressed_bundle_folder: ${decompressed_bundle_folder}"
echo "ref_genome: ${ref_genome}"
echo "dbsnp_138: ${dbsnp_138}"
echo ""
echo "targets_folder: ${targets_folder}"
echo "targets_intervals: ${targets_intervals}"
echo ""
echo "kgen_folder: ${kgen_folder}"
echo "kgen_split_vcf: ${kgen_split_vcf}"
echo ""
echo "exac_folder: ${exac_folder}"
echo "exac_non_tcga_split_vcf: ${exac_non_tcga_split_vcf}"
echo ""
echo "Working sub-folders on HPC"
echo "--------------------------"
echo ""
echo "project_folder: ${project_folder}"
echo "split_annotate_folder: ${split_annotate_folder}"
echo "tmp_folder: ${tmp_folder}"
echo ""
echo "Additional settings"
echo "-------------------"
echo ""
echo "vep_fields: ${vep_fields}"
echo ""
